Create database caps;
use caps;
show tables;
describe orders;
UPDATE staffs
SET manager_id = NULL
WHERE manager_id = 'NA';
SELECT * FROM STAFFS;
UPDATE orders
SET shipped_date = NULL
WHERE shipped_date = 'NA';

select * from order_items;
select * from products;  
select * from orders;
select * from stores;

##Inner Join for Order Details
## Join orders, order_items, and products to display detailed line items.

select o.order_id,p.product_id,d.customer_id,o.product_items,p.model_year
 from order_items as o
inner join products p on o.product_id = p.product_id
inner join orders d on d.order_id = o.order_id;

##- Write a query to group sales (total_price) by each store_id. 

select o.store_id,s.store_name, sum(oi.total_Sales) sales
from order_items oi
inner join orders o on o.order_id = oi.order_id
inner join stores s on s.store_id = o.store_id
group by o.store_id,s.store_name;

##-- Top 5 Selling Products  o Use ORDER BY and LIMIT to get the top 5 most sold products by quantity.
select product_items,sum(quantity) quantity
from order_items
group by product_items
order by quantity desc limit 5;

-- Customer Purchase Summary o For each customer, return total orders placed, total items purchased, and total revenue. 

##
Select concat(c.first_name," ", c.last_name) as customer_name, 
count(distinct(oi.order_id)) as total_orders, sum(oi.quantity) as total_items_purchased, 
sum(oi.total_sales) as total_revenue from orders as o
join customers1 as c on c.customer_id = o.customer_id
join order_items as oi on o.order_id = oi.order_id
group by c.customer_id ;

## -- Segment Customers by Total Spend o Write a query to classify customers into spending brackets (e.g., low, medium, high).  

select c.customer_id, concat(c.first_name,' ' , c.last_name) as customer_name,
sum(oi.total_sales)total_spending,
case 
when sum(oi.total_sales)<8000 then 'Low'
when sum(oi.total_sales)between 8000 and 15000 then 'Medium'
else 'High'
end spending_segment
from customers1 c
inner join orders o on o.customer_id= c.customer_id
inner join order_items oi on oi.order_id= o.order_id
group by customer_id,c.first_name,c.last_name
order by sum(oi.total_sales);

##Staff Performance Analysis o Analyze total revenue generated by each staff member based on their handled orders.

select s.staff_id,concat(s.first_name,' ',s.last_name) staff_name, sum(oi.total_sales)
total_revenue,
case
	when sum(oi.total_sales) is null then 'No_sales'
    when sum(oi.total_sales) < 100000 then 'Poor'
    when sum(oi.total_sales) between 100000 and 1000000 then 'Average'
    else 'good'
    end staff_performance
    from staffs s
    left join orders o on o.staff_id = s.staff_id
    left join order_items oi on oi.order_id = o.order_id
group by s.staff_id, s.first_name, s.last_name
order by sum(oi.total_sales);

